---
title: 'Documento de analisis de datos para trabajo: Migracion y vivienda: estudio de los costos de arriendo para el 2017'
author: "Venegas, M; Dimter, J; Lafferte, A; Esturillo, D"
date: "25 de noviembre de 2019"
output: html_document
---
# Resumen  
En el presente documento se analizan los datos de la base de datos CASEN 2017 procesada anteriormente, con el fin de construir el informe futuro.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Carga Paquetes}
#Datos CASEN 2017#
#Instalacion de librerias
pacman::p_load(ggplot2,plotly, dplyr, stargazer, texreg, corrplot, haven, sjlabelled, psych, writexl, ggmosaic, DescTools, lme4, lmerTest)
pacman::p_load(kableExtra, pander, descr, expss,car, foreign,ggcorrplot, webshot, sessioninfo)
```

```{r Carga BD}
# Cargar base de datos
load("../input/data/df_arriendos.RData")

df_arriendos <- sjlabelled::remove_all_labels(df_arriendos)
```

```{r Descriptivos univariados}
# Tablas variables de control
#a) Sexo
tabla_sexo <- freq(df_arriendos$sexo_rec)
write.xlsx(tabla_sexo, "../output/tables/tabla_sexo.xlsx")

#b) Origen
tabla_origen <- freq(df_arriendos$origen)
write.xlsx(tabla_origen, "../output/tables/tabla_origen.xlsx")

#c) Cantidad Banos
tabla_cant_banos <- freq(df_arriendos$cant_banos)
write.xlsx(tabla_cant_banos, "../output/tables/tabla_cant_banos.xlsx")

#d) Cantidad Dormitorios
tabla_cant_dorm <- freq(df_arriendos$cant_dorm)
write.xlsx(tabla_cant_dorm, "../output/tables/tabla_cant_dorm.xlsx")

#e) Ano llegada
tabla_ano_llegada <- freq(df_arriendos$ano_llegada)
write.xlsx(tabla_ano_llegada, "../output/tables/tabla_ano_llegada.xlsx")

#f) Muros
tabla_muros_rec <- freq(df_arriendos$muros_rec)
write.xlsx(tabla_muros_rec, "../output/tables/tabla_muros_rec.xlsx")

#g) Tipo Uso (Arriendo)
tabla_tipo_uso_rec <- freq(df_arriendos$tipo_uso_rec)
write.xlsx(tabla_tipo_uso_rec, "../output/tables/tabla_tipo_uso_rec.xlsx")

#h) Contrato
tabla_contrato_rec <- freq(df_arriendos$contrato_rec)
write.xlsx(tabla_contrato_rec, "../output/tables/tabla_contrato_rec.xlsx")

#i) Mt2_vivienda
tabla_Mt2_vivienda_rec <- freq(df_arriendos$Mt2_vivienda_rec)
write.xlsx(tabla_Mt2_vivienda_rec, "../output/tables/tabla_Mt2_vivienda_rec.xlsx")

#j) Acceso a Servicios
tabla_acceso_servicios <- freq(df_arriendos$acceso_servicios)
write.xlsx(tabla_acceso_servicios, "../output/tables/tabla_acceso_servicios.xlsx")

# Graficos
#) Ingresos
ging <- df_arriendos %>% ggplot( aes(x=ingresos)) +
    geom_density(fill="#69b3a2", color="#e9ecef", alpha=0.8) +
    ggtitle("Ingresos de poblacion migrante que mantiene arriendo")+ scale_x_continuous(limits = c(0,3600000))

ggsave("../output/graphs/grafico_ingresos.png", ging)

#) Costo Arriendo
gcost <- df_arriendos %>% ggplot(aes(x=costo_arr)) + geom_density(fill="#69b3a2", color="#e9ecef", alpha=1) + ggtitle("Distribucion costo de arriendo")

ggsave("../output/graphs/grafico_costos.png", gcost)

#) Acceso a servicios
gacc <- df_arriendos %>% ggplot(aes(x=acceso_servicios)) + geom_density(fill="#69b3a2", color="#e9ecef", alpha=1) + ggtitle("Distribucion indice de acceso a servicios")

ggsave("../output/graphs/grafico_acceso.png", gacc)

#) Ingreso comunal promedio
gingc <- df_arriendos %>% ggplot(aes(x=mean_ing_comuna)) + geom_density(fill="#69b3a2", color="#e9ecef", alpha=1) + ggtitle("Distribucion Ingreso comunal promedio")

ggsave("../output/graphs/grafico_ingresos_comuna.png", gingc)

#) Porcentaje de arriendo sin contrato por comuna
gpsinc <- df_arriendos %>% ggplot(aes(x=sin_contrato_comuna)) + geom_density(fill="#69b3a2", color="#e9ecef", alpha=1) + ggtitle("Distribucion Porcentaje de arriendo sin contrato por comuna")

ggsave("../output/graphs/grafico_porcentaje_sincontrato_com.png", gpsinc)

#) Porcentaje de migrantes por comuna
gpmc <- df_arriendos %>% ggplot(aes(x=porc_migr_comuna)) + geom_density(fill="#69b3a2", color="#e9ecef", alpha=1) + ggtitle("Distribucion Porcentaje de migrantes por comuna")

ggsave("../output/graphs/grafico_porcentaje_migrantes_com.png", gpmc)

#) Promedio de acceso a servicios a nivel comunal
gaccc <- df_arriendos %>% ggplot(aes(x=acceso_comunal)) + geom_density(fill="#69b3a2", color="#e9ecef", alpha=1) + ggtitle("Distribucion Promedio de acceso a servicios a nivel comunal")

ggsave("../output/graphs/grafico_acceso_com.png", gaccc)
```

```{r Descriptivos bivriados: Scatter plots}
scatterplot(df_arriendos$costo_arr ~ as.factor(df_arriendos$origen), data=df_arriendos, xlab="Origen", ylab="Costo arriendo", main="Costo arriendo por origen", smooth=FALSE)


```

```{r}
scatterplot(df_arriendos$costo_arr ~ df_arriendos$tipo_uso, data=df_arriendos, xlab="Tipo de uso de la vivienda", ylab="Costo de arriendo", main="Costo arriendo por tipo de uso", smooth=FALSE)
```

```{r}
scatterplot(df_arriendos$costo_arr ~ df_arriendos$sexo, data=df_arriendos, xlab="Sexo", ylab="Costo arriendo", main="Costo arriendo por sexo", smooth=FALSE)
```

```{r}
scatterplot(df_arriendos$costo_arr ~ df_arriendos$ingresos, data=df_arriendos, xlab="Ingresos", ylab="Costo arriendo", main="Costo arriendo por ingresos", smooth=FALSE)
```

```{r}
scatterplot(df_arriendos$costo_arr ~ df_arriendos$contrato, data=df_arriendos, xlab="Contrato", ylab="Costo arriendo", main="Costo arriendo por contrato", smooth=FALSE)
```

```{r Matriz correlaciones para costo arriendo y variables de control sobre caracteristicas de la vivienda}
cor_viv<-cor(df_arriendos[c("costo_arr", "muros", "Mt2_vivienda", "cant_dorm", "cant_banos")], use="complete")
ggcorrplot(cor_viv, hc.order = TRUE, type = "full",lab=TRUE,colors = c("#439BD1", "white", "#FF6C6C"),lab_size=2,tl.cex=8)
```

```{r Matriz de correlaciones para variables a nivel individual}
BDcor <- df_arriendos
BDcor$sexo <- as.numeric(BDcor$sexo)
BDcor$origen <- as.numeric(BDcor$origen)
cor_ind<-cor(BDcor[c("sexo","origen","ano_llegada","ingresos","contrato","acceso_servicios","muros","Mt2_vivienda","cant_banos","cant_dorm")], use="complete")
ggcorrplot(cor_ind, hc.order = TRUE, type = "full",lab=TRUE,colors = c("#439BD1", "white", "#FF6C6C"),lab_size=2,tl.cex=8)
```

```{r Matriz de correlaciones para variables a nivel comunal}
cor_com<-cor(df_arriendos[c("costo_arr", "mean_ing_comuna", "sin_contrato_comuna","acceso_comunal","porc_migr_comuna")], use="complete")
ggcorrplot(cor_com, hc.order = TRUE, type = "full",lab=TRUE,colors = c("#439BD1", "white", "#FF6C6C"),lab_size=2,tl.cex=8)
```

```{r Analisis Multivariado, eval=FALSE, include=FALSE}

```

```{r Modelo nulo + ICC}
results_0a <- lmer(costo_arr ~ 1 + (1 |comuna), data = df_arriendos)
reghelper::ICC(results_0a)
#screenreg(results_0a)
htmlreg(results_0a, file = "../output/tables/results_0a.html", 
inline.css = FALSE, doctype = TRUE, html.tag = TRUE, 
head.tag = TRUE, body.tag = TRUE)
```

```{r Modelo 1 con predictores de nivel 1}
results_1 = lmer(costo_arr ~ 1 + sexo + origen + ano_llegada + tipo_uso_rec + ingresos + contrato_rec + acceso_servicios + muros_rec + Mt2_vivienda_rec + cant_banos + cant_dorm + (1 | comuna), data = df_arriendos)
levels((df_arriendos$origen))
label_lvl1 <- c("Intercepto","Sexo","Centroamerica y el Caribe","Sudamerica","Ano de llegada","Arriendo sin contrato","Monto de ingresos","Tiene contrato laboral sin firmar","No tiene contrato","indice de acceso a servicios","Muro de Albanileria (bloque de cemento, piedra o ladrillo)","Muro de Tabique forrado por ambas caras (madera, acero, lata u otro)","Muro de Tabique sin forro interior (madera u otro)","Muro de Adobe, barro, quincha, pirca u otro artesanal tradicional","30 a 40 m2","41 a 60 m2","61 a 100 m2","101 a 150 m2","Mas de 150 m2", "Cantidad de banos","Cantidad de dormitorios")
screenreg(c(results_0a,results_1), naive=TRUE, custom.coef.names = label_lvl1)
htmlreg(results_1, file = "../output/tables/results_1.html", 
inline.css = FALSE, doctype = TRUE, html.tag = TRUE, head.tag = TRUE, body.tag = TRUE, custom.coef.names = label_lvl1)
```

```{r Modelo 2 con predictores de nivel 2}
results_2 = lmer(costo_arr ~ 1 + mean_ing_comuna + sin_contrato_comuna + porc_migr_comuna +acceso_comunal+ (1 | comuna), data = df_arriendos)
label_lvl2 <- c("Intercepto","Ingreso promedio comunal","Porcentaje de arriendo sin contrato comunal","Porcentaje de poblacion migrante comunal","Acceso a servicios promedio comunal")
screenreg(results_2, naive=TRUE,custom.coef.names = label_lvl2)

htmlreg(results_2, file = "../output/tables/results_2.html", 
inline.css = FALSE, doctype = TRUE, html.tag = TRUE, head.tag = TRUE, body.tag = TRUE,custom.coef.names = label_lvl2)
```

```{r Modelo 3 con predictores de nivel 1 y 2}
results_3 = lmer(costo_arr ~ 1 + sexo + origen + ano_llegada + tipo_uso_rec + ingresos + contrato_rec + acceso_servicios + muros_rec + Mt2_vivienda_rec + cant_banos + cant_dorm + (1 | comuna) + mean_ing_comuna + sin_contrato_comuna + porc_migr_comuna +acceso_comunal, data = df_arriendos)
label_lvl12 <- c("Intercepto","Sexo","Centroamerica y el Caribe","Sudamerica","Ano de llegada","Arriendo sin contrato","Monto de ingresos","Tiene contrato laboral sin firmar","No tiene contrato","indice de acceso a servicios","Muro de Albanileria (bloque de cemento, piedra o ladrillo)","Muro de Tabique forrado por ambas caras (madera, acero, lata u otro)","Muro de Tabique sin forro interior (madera u otro)","Muro de Adobe, barro, quincha, pirca u otro artesanal tradicional","30 a 40 m2","41 a 60 m2","61 a 100 m2","101 a 150 m2","Mas de 150 m2", "Cantidad de banos","Cantidad de dormitorios","Ingreso promedio comunal","Porcentaje de arriendo sin contrato comunal","Porcentaje de poblacion migrante comunal","Acceso a servicios promedio comunal")
#screenreg(results_3, naive=TRUE,custom.coef.names = label_lvl12)
htmlreg(results_3, file = "../output/tables/results_3.html", 
inline.css = FALSE, doctype = TRUE, html.tag = TRUE, 
head.tag = TRUE, body.tag = TRUE,custom.coef.names = label_lvl12)
```

```{r Modelo 4 con efectos aleatorios}
results_4 = lmer(costo_arr ~ 1 + sexo + origen + ano_llegada + tipo_uso_rec + ingresos + contrato_rec + acceso_servicios + muros_rec + Mt2_vivienda_rec + cant_banos + cant_dorm + (1 + origen | comuna) + mean_ing_comuna + sin_contrato_comuna + porc_migr_comuna +acceso_comunal, data = df_arriendos)

#screenreg(results_4, naive=TRUE)

htmlreg(results_4, file = "../output/tables/results_4.html", 
inline.css = FALSE, doctype = TRUE, html.tag = TRUE, 
head.tag = TRUE, body.tag = TRUE,custom.coef.names = label_lvl12)
```


```{r Modelo 5 interacci?n entre niveles}
#Antes de hacer el modelo:
anova(results_3,results_4)

#Modelo
results_5 = lmer(costo_arr ~ 1 + sexo + origen + ano_llegada + tipo_uso_rec + ingresos + contrato_rec + acceso_servicios + muros_rec + Mt2_vivienda_rec + cant_banos + cant_dorm + (1 + origen | comuna) + mean_ing_comuna + sin_contrato_comuna + porc_migr_comuna +acceso_comunal+ origen*sin_contrato_comuna + origen*acceso_comunal, data = df_arriendos)

label_intera <- c("Intercepto","Sexo","Centroamerica y el Caribe","Sudamerica","Ano de llegada","Arriendo sin contrato","Monto de ingresos","Tiene contrato laboral sin firmar","No tiene contrato","indice de acceso a servicios","Muro de Albanileria (bloque de cemento, piedra o ladrillo)","Muro de Tabique forrado por ambas caras (madera, acero, lata u otro)","Muro de Tabique sin forro interior (madera u otro)","Muro de Adobe, barro, quincha, pirca u otro artesanal tradicional","30 a 40 m2","41 a 60 m2","61 a 100 m2","101 a 150 m2","Mas de 150 m2", "Cantidad de banos","Cantidad de dormitorios","Ingreso promedio comunal","Porcentaje de arriendo sin contrato comunal","Porcentaje de poblacion migrante comunal","Acceso a servicios promedio comunal","Centroamerica y el Caribe * %Arriendo sin contrato comunal","Sudamerica * %Arriendo sin contrato comunal","Centroamerica y el Caribe * Acceso a servicios promedio comunal","Sudamerica * Acceso a servicios promedio comunal")
htmlreg(results_5, file = "../output/tables/results_5.html", 
inline.css = FALSE, doctype = TRUE, html.tag = TRUE, 
head.tag = TRUE, body.tag = TRUE)


```


```{r Tabla lista modelos}
htmlreg(c(results_0a,results_3,results_4,results_5), file = "../output/tables/results_modelos.html", 
inline.css = FALSE, doctype = TRUE, html.tag = TRUE, 
head.tag = TRUE, body.tag = TRUE,custom.coef.names = label_intera,custom.model.names
= c("Modelo Nulo","Modelo mixto fijo","Modelo mixto aleatorio","Modelo Interaccion"))
```

```{r Tabla modelos a png, eval=FALSE, include=FALSE}
webshot("../output/tables/results_modelos.html","../input/images/results_modelos.png")
```

```{r Información de la sesión, include=FALSE}
sessionInfo()
session_info("sessioninfo")$platform
package_info(pkgs = (.packages()), dependencies = FALSE)

```

